#!-*-coding:utf-8-*-
# !@Date: 2018/11/17 10:29
# !@Author: Liu Rui
# !@github: bigfoolliu


"""
了解jsonpath的使用
"""
import json

from jsonpath import jsonpath


# json字符串
json_str = {
  "success": 'true',
  "requestId": 'null',
  "resubmitToken": 'null',
  "msg": 'null',
  "code": 0,
  "content": {
    "pageNo": 2,
    "pageSize": 15,
    "hrInfoMap": {
      "3211888": {
        "userId": 2386087,
        "positionName": "HR",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "冯磊",
        "portrait": "i/image2/M00/1F/67/CgotOVoNEW6AIuBzAAAe8kpRHnU013.jpg",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "3477944": {
        "userId": 383355,
        "positionName": "人力负责人",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "陈小姐",
        "portrait": "i/image/M00/7A/D2/CgpEMlpEniSAIDJLAABB7cAFJpI389.png",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "4042527": {
        "userId": 602993,
        "positionName": "招聘经理",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "Cherry",
        "portrait": "i/image2/M01/A5/95/CgotOVvfsi6ABZ8DAAAa3Mpg5U0664.png",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "4123246": {
        "userId": 1420174,
        "positionName": "HR",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "Yan.Sun",
        "portrait": "i/image3/M00/3C/CB/Cgq2xlqvlGuAaOoRAAAwAEJsj04244.jpg",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "4571355": {
        "userId": 8447386,
        "positionName": "HRM",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "Rocky",
        "portrait": "i/image2/M00/21/6E/CgotOVoSsD2AUrxrAABKmxkrmb0905.png",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "4740360": {
        "userId": 10998875,
        "positionName": "HR",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "王经理",
        "portrait": "i/image2/M01/7E/BA/CgotOVt6dqOAZrsyAAAwKVdZOTs625.jpg",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "4869259": {
        "userId": 7751569,
        "positionName": "",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "HR",
        "portrait": 'null',
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "5021841": {
        "userId": 895780,
        "positionName": "HR",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "会分期",
        "portrait": "i/image2/M01/94/74/CgotOVuvYLuATnmjAABw0yCP6zY103.png",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "5153937": {
        "userId": 8054974,
        "positionName": "联合创始人",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "叶泽轩",
        "portrait": "i/image2/M01/8F/77/CgotOVugvCCANUReAACod7rYutM180.png",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "5244706": {
        "userId": 2123209,
        "positionName": "HR",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "原力互娱-王小姐",
        "portrait": "i/image2/M01/A9/DC/CgotOVvqNVCAX9XUAAAT0ytsJFA198.jpg",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "5267750": {
        "userId": 1621385,
        "positionName": "HR Manager",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "Stephanie",
        "portrait": "i/image3/M00/27/14/Cgq2xlqZFzaAX7vQAAA56g3Qhow603.png",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "5276211": {
        "userId": 3618375,
        "positionName": "HR",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "summer",
        "portrait": "i/image2/M01/90/45/CgotOVuiR7uAEdmwAADFH51mWEc203.png",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "5297689": {
        "userId": 9168390,
        "positionName": "HR",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "HR",
        "portrait": "i/image2/M01/97/15/CgoB5lu8hreAWuoXAABaqgd--vA136.jpg",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "5314259": {
        "userId": 11421799,
        "positionName": "人事专员",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "明郁川",
        "portrait": "i/image2/M01/7F/29/CgotOVt7eiuAAEEaAAB0XDFPWL8349.jpg",
        "userLevel": "G1",
        "canTalk": 'true'
      },
      "5331740": {
        "userId": 6407119,
        "positionName": "招聘经理",
        "phone": 'null',
        "receiveEmail": 'null',
        "realName": "Jeff",
        "portrait": 'null',
        "userLevel": "G1",
        "canTalk": 'true'
      }
    },
    "positionResult": {
      "totalCount": 24461,
      "queryAnalysisInfo": {
        "positionName": "python",
        "jobNature": 'null',
        "companyName": 'null',
        "industryName": 'null',
        "usefulCompany": 'false'
      },
      "strategyProperty": {
        "name": "dm-csearch-useUserAllInterest",
        "id": 1
      },
      "hotLabels": 'null',
      "hiTags": 'null',
      "locationInfo": {
        "city": 'null',
        "district": 'null',
        "queryByGisCode": 'false',
        "businessZone": 'null',
        "locationCode": 'null',
        "isAllhotBusinessZone": 'false'
      },
      "resultSize": 15,
      "result": [
        {
          "companyId": 173177,
          "positionName": "python开发",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "113.331592",
          "latitude": "23.115529",
          "financeStage": "天使轮",
          "companySize": "50-150人",
          "companyLogo": "i/image/M00/1B/42/CgpFT1kJVXyALGLxAAFexBnuhDs088.png",
          "industryField": "游戏",
          "companyShortName": "BBGAME",
          "city": "广州",
          "salary": "10k-15k",
          "positionId": 5297689,
          "positionAdvantage": "晋升快,薪资高,福利好,上司nice",
          "createTime": "2018-11-15 16:01:28",
          "district": "天河区",
          "score": 0,
          "approve": 1,
          "positionLables": [],
          "industryLables": [],
          "publisherId": 9168390,
          "companyLabelList": [
            "年底双薪",
            "绩效奖金",
            "领导好",
            "扁平管理"
          ],
          "businessZones": 'null',
          "formatCreateTime": "2天前发布",
          "companyFullName": "广州黑胡子游戏开发有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "APM线",
          "stationname": "妇儿中心",
          "linestaion": "3号线_广州塔;3号线_珠江新城;5号线_珠江新城;5号线_猎德;5号线_潭村;APM线_海心沙;APM线_大剧院;APM线_花城大道;APM线_妇儿中心;APM线_黄埔大道",
          "thirdType": "Python",
          "skillLables": [],
          "hitags": 'null',
          "resumeProcessRate": 6,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542417618000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 22481,
          "positionName": "Python开发师",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "121.42788",
          "latitude": "31.19456",
          "financeStage": "B轮",
          "companySize": "150-500人",
          "companyLogo": "i/image2/M01/98/55/CgotOVu-7sGAAhf-AABzbAALq7A126.png",
          "industryField": "移动互联网",
          "companyShortName": "问卷网@爱调研",
          "city": "上海",
          "salary": "15k-30k",
          "positionId": 4042527,
          "positionAdvantage": "五险一金,季度旅游,节日福利,带薪年假",
          "createTime": "2018-11-16 17:03:39",
          "district": "徐汇区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "Java"
          ],
          "industryLables": [],
          "publisherId": 602993,
          "companyLabelList": [
            "技能培训",
            "节日礼物",
            "年底双薪",
            "绩效奖金"
          ],
          "businessZones": 'null',
          "formatCreateTime": "1天前发布",
          "companyFullName": "上海众言网络科技有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "11号线(花桥)",
          "stationname": "虹桥路",
          "linestaion": "1号线_徐家汇;3号线_虹桥路;3号线_宜山路;4号线_虹桥路;9号线_徐家汇;9号线_宜山路;10号线(航中路)_交通大学;10号线(航中路)_虹桥路;10号线(虹桥火车站)_交通大学;10号线(虹桥火车站)_虹桥路;11号线(嘉定北)_徐家汇;11号线(嘉定北)_交通大学;11号线(花桥)_徐家汇;11号线(花桥)_交通大学",
          "thirdType": "Python",
          "skillLables": [
            "Java"
          ],
          "hitags": 'null',
          "resumeProcessRate": 20,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542359022000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 121222,
          "positionName": "Python开发工程师",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "121.457082",
          "latitude": "31.278464",
          "financeStage": "上市公司",
          "companySize": "2000人以上",
          "companyLogo": "i/image/M00/18/45/Cgp3O1bzhIyAPaTmAAC7RITtIAU540.PNG",
          "industryField": "移动互联网,电子商务",
          "companyShortName": "易居中国-创新研发中心",
          "city": "上海",
          "salary": "15k-25k",
          "positionId": 5331740,
          "positionAdvantage": "上市公司,创新项目,平台大,技术牛",
          "createTime": "2018-11-15 18:16:03",
          "district": "闸北区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "图像处理",
            "机器学习"
          ],
          "industryLables": [],
          "publisherId": 6407119,
          "companyLabelList": [
            "技能培训",
            "岗位晋升",
            "五险一金",
            "14薪"
          ],
          "businessZones": 'null',
          "formatCreateTime": "2天前发布",
          "companyFullName": "上海鋆创信息技术有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "1号线",
          "stationname": "延长路",
          "linestaion": "1号线_延长路;1号线_上海马戏城",
          "thirdType": "Python",
          "skillLables": [
            "图像处理",
            "机器学习"
          ],
          "hitags": 'null',
          "resumeProcessRate": 6,
          "resumeProcessDay": 0,
          "imState": "today",
          "lastLogin": 1542365877000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 19209,
          "positionName": "python开发工程师",
          "workYear": "3-5年",
          "education": "大专",
          "jobNature": "全职",
          "longitude": "113.400891",
          "latitude": "23.118987",
          "financeStage": "A轮",
          "companySize": "15-50人",
          "companyLogo": "i/image/M00/84/1D/Cgp3O1hbjFmAHHLvAABB7cAFJpI050.png",
          "industryField": "生活服务",
          "companyShortName": "省省回头车",
          "city": "广州",
          "salary": "15k-22k",
          "positionId": 3477944,
          "positionAdvantage": "周末双休,弹性工作,五险齐全,带薪年假",
          "createTime": "2018-11-15 10:40:53",
          "district": "天河区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "云计算",
            "云计算"
          ],
          "industryLables": [
            "云计算",
            "云计算"
          ],
          "publisherId": 383355,
          "companyLabelList": [
            "绩效奖金",
            "五险一金",
            "通讯津贴",
            "带薪年假"
          ],
          "businessZones": [
            "车陂",
            "东圃",
            "前进"
          ],
          "formatCreateTime": "2天前发布",
          "companyFullName": "广州回头车信息科技有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "4号线",
          "stationname": "车陂南",
          "linestaion": "4号线_车陂;4号线_车陂南;5号线_车陂南;5号线_东圃",
          "thirdType": "C|C++",
          "skillLables": [
            "云计算"
          ],
          "hitags": 'null',
          "resumeProcessRate": 100,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542363858000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 126248,
          "positionName": "python开发工程师",
          "workYear": "3-5年",
          "education": "大专",
          "jobNature": "全职",
          "longitude": "113.370887",
          "latitude": "23.124949",
          "financeStage": "上市公司",
          "companySize": "500-2000人",
          "companyLogo": "i/image2/M01/88/FA/CgotOVuSHtGAFtsIAADTS30Vdog514.jpg",
          "industryField": "移动互联网",
          "companyShortName": "原力互娱",
          "city": "广州",
          "salary": "15k-20k",
          "positionId": 5244706,
          "positionAdvantage": "上市公司,周末双休,包三餐,团队氛围好",
          "createTime": "2018-11-16 10:27:10",
          "district": "天河区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "游戏",
            "运维",
            "Linux"
          ],
          "industryLables": [
            "游戏",
            "运维",
            "Linux"
          ],
          "publisherId": 2123209,
          "companyLabelList": [
            "绩效奖金",
            "带薪年假",
            "年底双薪",
            "弹性工作"
          ],
          "businessZones": [
            "员村",
            "天河公园",
            "棠下"
          ],
          "formatCreateTime": "1天前发布",
          "companyFullName": "广州原力互娱网络科技有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "运维",
          "isSchoolJob": 0,
          "subwayline": "5号线",
          "stationname": "科韵路",
          "linestaion": "5号线_员村;5号线_科韵路",
          "thirdType": "运维开发工程师",
          "skillLables": [
            "运维",
            "Linux"
          ],
          "hitags": 'null',
          "resumeProcessRate": 100,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542338719000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 66398,
          "positionName": "Python开发工程师",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "120.993464",
          "latitude": "30.994061",
          "financeStage": "C轮",
          "companySize": "50-150人",
          "companyLogo": "i/image3/M00/1B/DE/CgpOIFp_sx2AKbPwAAA2OciLZMY734.jpg",
          "industryField": "电子商务",
          "companyShortName": "Student.com",
          "city": "上海",
          "salary": "15k-25k",
          "positionId": 5267750,
          "positionAdvantage": "活力团队，弹性工作，发展空间大",
          "createTime": "2018-11-15 16:50:46",
          "district": "静安区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "后端",
            "MySQL",
            "搜索"
          ],
          "industryLables": [],
          "publisherId": 1621385,
          "companyLabelList": [
            "技能培训",
            "带薪年假",
            "岗位晋升",
            "五险一金"
          ],
          "businessZones": [
            "同乐坊",
            "江宁路",
            "西康路"
          ],
          "formatCreateTime": "2天前发布",
          "companyFullName": "江曲投资咨询（上海）有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": 'null',
          "stationname": 'null',
          "linestaion": 'null',
          "thirdType": "Python",
          "skillLables": [
            "后端",
            "MySQL",
            "搜索"
          ],
          "hitags": 'null',
          "resumeProcessRate": 57,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542357020000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 300032,
          "positionName": "Python工程师",
          "workYear": "1-3年",
          "education": "大专",
          "jobNature": "全职",
          "longitude": "108.91059",
          "latitude": "34.214585",
          "financeStage": "未融资",
          "companySize": "150-500人",
          "companyLogo": "i/image2/M00/54/C1/CgoB5lsZ8keAM3FUAAAcW5xc3Dc140.jpg",
          "industryField": "电子商务",
          "companyShortName": "晟运通科技",
          "city": "西安",
          "salary": "8k-15k",
          "positionId": 4740360,
          "positionAdvantage": "五险一金,法定双休,节日福利,平台晋升",
          "createTime": "2018-11-09 12:01:16",
          "district": "雁塔区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "大数据",
            "Hadoop"
          ],
          "industryLables": [
            "大数据",
            "Hadoop"
          ],
          "publisherId": 10998875,
          "companyLabelList": [
            "年底双薪",
            "绩效奖金",
            "带薪年假",
            "节日礼物"
          ],
          "businessZones": [
            "科技二路",
            "电子城",
            "电子正街"
          ],
          "formatCreateTime": "2018-11-09",
          "companyFullName": "陕西晟运通科技有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "3号线",
          "stationname": "太白南路",
          "linestaion": "3号线_太白南路",
          "thirdType": "Java",
          "skillLables": [
            "Hadoop"
          ],
          "hitags": 'null',
          "resumeProcessRate": 11,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542331204000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 129842,
          "positionName": "Python开发工程师",
          "workYear": "1-3年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "114.424058",
          "latitude": "30.463068",
          "financeStage": "A轮",
          "companySize": "50-150人",
          "companyLogo": "i/image3/M00/53/FB/Cgq2xlsPbMOAcsgKAACneC-gdWQ891.png",
          "industryField": "移动互联网,社交网络",
          "companyShortName": "猫头鹰团队",
          "city": "武汉",
          "salary": "10k-15k",
          "positionId": 4571355,
          "positionAdvantage": "年终奖金,五险一金,弹性时间,零食水果",
          "createTime": "2018-11-16 10:28:29",
          "district": "江夏区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "Java",
            "MySQL"
          ],
          "industryLables": [],
          "publisherId": 8447386,
          "companyLabelList": [
            "带薪年假",
            "定期体检",
            "绩效奖金",
            "技能培训"
          ],
          "businessZones": 'null',
          "formatCreateTime": "1天前发布",
          "companyFullName": "武汉猫鹰科技有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": 'null',
          "stationname": 'null',
          "linestaion": 'null',
          "thirdType": "Python",
          "skillLables": [
            "Java",
            "MySQL"
          ],
          "hitags": 'null',
          "resumeProcessRate": 10,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542363637000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 292614,
          "positionName": "高级python开发",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "104.0652",
          "latitude": "30.581174",
          "financeStage": "未融资",
          "companySize": "500-2000人",
          "companyLogo": "i/image2/M01/7A/C2/CgotOVtxCruARUN2AAB6-Rljn0A653.jpg",
          "industryField": "移动互联网",
          "companyShortName": "金蜜工业卫士",
          "city": "成都",
          "salary": "10k-20k",
          "positionId": 5314259,
          "positionAdvantage": "五险一金,周末双休,零食供应,团队氛围好",
          "createTime": "2018-11-14 09:05:44",
          "district": "高新区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "金融",
            "后端"
          ],
          "industryLables": [
            "金融",
            "后端"
          ],
          "publisherId": 11421799,
          "companyLabelList": [
            "\"\""
          ],
          "businessZones": 'null',
          "formatCreateTime": "3天前发布",
          "companyFullName": "乐山金蜜工业卫士服务股份有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "1号线",
          "stationname": "孵化园",
          "linestaion": "1号线_孵化园;1号线_金融城;1号线_高新",
          "thirdType": "Python",
          "skillLables": [
            "后端"
          ],
          "hitags": 'null',
          "resumeProcessRate": 16,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542414858000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 452635,
          "positionName": "Python研发工程师",
          "workYear": "1-3年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "116.322239",
          "latitude": "39.992047",
          "financeStage": "天使轮",
          "companySize": "少于15人",
          "companyLogo": "i/image2/M01/8F/E3/CgotOVuhxbKAcy2vAACod7rYutM434.png",
          "industryField": "医疗健康,硬件",
          "companyShortName": "颐邦科技",
          "city": "北京",
          "salary": "15k-25k",
          "positionId": 5153937,
          "positionAdvantage": "团队优秀,技术强,薪酬高,福利好",
          "createTime": "2018-11-05 15:50:24",
          "district": "海淀区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "Java",
            "Golang",
            "后端"
          ],
          "industryLables": [],
          "publisherId": 8054974,
          "companyLabelList": [
            "\"\""
          ],
          "businessZones": [
            "清华大学",
            "北京大学",
            "中关村"
          ],
          "formatCreateTime": "2018-11-05",
          "companyFullName": "颐邦（北京）医院管理有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "13号线",
          "stationname": "五道口",
          "linestaion": "4号线大兴线_中关村;4号线大兴线_北京大学东门;4号线大兴线_圆明园;13号线_五道口",
          "thirdType": "Python",
          "skillLables": [
            "Java",
            "Golang",
            "后端"
          ],
          "hitags": 'null',
          "resumeProcessRate": 65,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542354170000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 35796,
          "positionName": "Python开发工程师",
          "workYear": "3-5年",
          "education": "大专",
          "jobNature": "全职",
          "longitude": "104.067729",
          "latitude": "30.546547",
          "financeStage": "A轮",
          "companySize": "50-150人",
          "companyLogo": "image1/M00/23/4D/Cgo8PFVHr2WADI5lAACQ3lRKz38637.png",
          "industryField": "移动互联网,企业服务",
          "companyShortName": "易路",
          "city": "成都",
          "salary": "8k-15k",
          "positionId": 3211888,
          "positionAdvantage": "弹性工时/年轻团队/人性管理/高端客户群",
          "createTime": "2018-11-16 09:50:48",
          "district": "高新区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "Java"
          ],
          "industryLables": [],
          "publisherId": 2386087,
          "companyLabelList": [
            "技能培训",
            "年底双薪",
            "绩效奖金",
            "岗位晋升"
          ],
          "businessZones": [
            "中和"
          ],
          "formatCreateTime": "1天前发布",
          "companyFullName": "上海易路软件有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "1号线",
          "stationname": "世纪城",
          "linestaion": "1号线_天府五街;1号线_天府三街;1号线_世纪城",
          "thirdType": "Python",
          "skillLables": [
            "Java"
          ],
          "hitags": 'null',
          "resumeProcessRate": 0,
          "resumeProcessDay": 0,
          "imState": "today",
          "lastLogin": 1542358496000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 56474,
          "positionName": "Python工程师",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "121.602093",
          "latitude": "31.199523",
          "financeStage": "B轮",
          "companySize": "50-150人",
          "companyLogo": "image2/M00/02/1E/CgpzWlXm-XaAQHV4AAAQGBL2IJs296.jpg",
          "industryField": "移动互联网,电子商务",
          "companyShortName": "NextTao 互道信息",
          "city": "上海",
          "salary": "18k-35k",
          "positionId": 4123246,
          "positionAdvantage": "技术前沿,大数据平台",
          "createTime": "2018-11-15 09:49:33",
          "district": "浦东新区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "Java"
          ],
          "industryLables": [],
          "publisherId": 1420174,
          "companyLabelList": [
            "节日礼物",
            "技能培训",
            "年底双薪",
            "年度旅游"
          ],
          "businessZones": [
            "张江"
          ],
          "formatCreateTime": "2天前发布",
          "companyFullName": "互道信息技术（上海）有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "2号线",
          "stationname": "张江高科",
          "linestaion": "2号线_金科路;2号线_张江高科",
          "thirdType": "其他后端开发",
          "skillLables": [
            "Java"
          ],
          "hitags": 'null',
          "resumeProcessRate": 78,
          "resumeProcessDay": 1,
          "imState": "disabled",
          "lastLogin": 1542246596000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 5946,
          "positionName": "python开发工程师",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "116.46044",
          "latitude": "39.961372",
          "financeStage": "D轮及以上",
          "companySize": "150-500人",
          "companyLogo": "i/image2/M01/74/AF/CgotOVthgLeAdUgqAAFHCuwRH30573.png",
          "industryField": "移动互联网,游戏",
          "companyShortName": "赤子城",
          "city": "北京",
          "salary": "15k-25k",
          "positionId": 4869259,
          "positionAdvantage": "七险一金,绩效奖金,发展空间,团队氛围",
          "createTime": "2018-11-16 15:53:11",
          "district": "朝阳区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "游戏",
            "社交"
          ],
          "industryLables": [
            "游戏",
            "社交"
          ],
          "publisherId": 7751569,
          "companyLabelList": [
            "学习氛围好",
            "扁平管理",
            "交通方便",
            "各种旅行福利"
          ],
          "businessZones": [
            "亮马桥",
            "三元桥",
            "燕莎"
          ],
          "formatCreateTime": "1天前发布",
          "companyFullName": "赤子城网络技术（北京）有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "10号线",
          "stationname": "亮马桥",
          "linestaion": "10号线_三元桥;10号线_亮马桥;机场线_三元桥",
          "thirdType": "Python",
          "skillLables": [],
          "hitags": 'null',
          "resumeProcessRate": 74,
          "resumeProcessDay": 1,
          "imState": "disabled",
          "lastLogin": 1542355536000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 46399,
          "positionName": "Python开发工程师(J10100)",
          "workYear": "3-5年",
          "education": "大专",
          "jobNature": "全职",
          "longitude": "116.301362",
          "latitude": "40.054996",
          "financeStage": "D轮及以上",
          "companySize": "150-500人",
          "companyLogo": "i/image2/M01/94/71/CgotOVuvV5GAF_ocAAB-N0BEjbk164.png",
          "industryField": "移动互联网、金融",
          "companyShortName": "会分期",
          "city": "北京",
          "salary": "15k-30k",
          "positionId": 5021841,
          "positionAdvantage": "五险一金,十四薪,弹性工作",
          "createTime": "2018-11-16 10:11:00",
          "district": "海淀区",
          "score": 0,
          "approve": 1,
          "positionLables": [
            "电商",
            "房产服务"
          ],
          "industryLables": [
            "电商",
            "房产服务"
          ],
          "publisherId": 895780,
          "companyLabelList": [
            "节日礼物",
            "股票期权",
            "带薪年假",
            "年度旅游"
          ],
          "businessZones": [
            "西二旗",
            "龙泽",
            "回龙观"
          ],
          "formatCreateTime": "1天前发布",
          "companyFullName": "会找房（北京）网络技术有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "昌平线",
          "stationname": "西二旗",
          "linestaion": "13号线_西二旗;昌平线_西二旗",
          "thirdType": "Python",
          "skillLables": [],
          "hitags": 'null',
          "resumeProcessRate": 10,
          "resumeProcessDay": 3,
          "imState": "today",
          "lastLogin": 1542357601000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        },
        {
          "companyId": 454120,
          "positionName": "Python研发工程师",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "longitude": "116.45187",
          "latitude": "39.96333",
          "financeStage": "上市公司",
          "companySize": "150-500人",
          "companyLogo": "i/image2/M01/90/01/CgoB5luh62-AL69UAAB7dJzUiiE996.png",
          "industryField": "移动互联网",
          "companyShortName": "听云",
          "city": "北京",
          "salary": "17k-24k",
          "positionId": 5276211,
          "positionAdvantage": "上市公司 带薪年假 地铁周边",
          "createTime": "2018-11-16 16:52:55",
          "district": "朝阳区",
          "score": 0,
          "approve": 1,
          "positionLables": [],
          "industryLables": [],
          "publisherId": 3618375,
          "companyLabelList": [
            "\"\""
          ],
          "businessZones": [
            "太阳宫",
            "三元桥",
            "国展"
          ],
          "formatCreateTime": "1天前发布",
          "companyFullName": "北京基调网络股份有限公司",
          "adWord": 0,
          "gradeDescription": 'null',
          "promotionScoreExplain": 'null',
          "firstType": "开发|测试|运维类",
          "secondType": "后端开发",
          "isSchoolJob": 0,
          "subwayline": "10号线",
          "stationname": "太阳宫",
          "linestaion": "10号线_太阳宫;10号线_三元桥;机场线_三元桥",
          "thirdType": "Python",
          "skillLables": [],
          "hitags": 'null',
          "resumeProcessRate": 100,
          "resumeProcessDay": 1,
          "imState": "today",
          "lastLogin": 1542359510000,
          "explain": 'null',
          "plus": 'null',
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0
        }
      ]
    }
  }
}


# 进行jsonpath操作
result_list = jsonpath(json_str, '$..result')[0]
# print(result_list)

financeStage_list = jsonpath(json_str, '$..financeStage')
print(financeStage_list)
